/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.working;

import UI.working.LoginSignUpScreen;
import Backend.working.User;
import Backend.working.dataValidator;
import Backend.dbManager;
import UI.MainScreen;
import java.sql.SQLException;
import javax.swing.ImageIcon;

/**
 *
 * @author Kairav
 */
public class CreateScreen extends javax.swing.JFrame {

    /**
     * Creates new form Create
     */
    public CreateScreen(User inU, dbManager inManager) {
        initComponents();
        this.setLocationRelativeTo(null);
        dbm = inManager;
        customerOwnerbuttonGroup.add(ownerButton);
        customerOwnerbuttonGroup.add(customerButton);
        customerButton.setSelected(true);
        ImageIcon ic = new ImageIcon("Resources\\showPassword.jpg");
        showPassword.setIcon(ic);
        showCode.setIcon(ic);
        showOwnerCodeField(false);
        u = inU;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customerOwnerbuttonGroup = new javax.swing.ButtonGroup();
        showPassword = new javax.swing.JLabel();
        dragPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        exitLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        ownerButton = new javax.swing.JRadioButton();
        customerButton = new javax.swing.JRadioButton();
        ownerOrCustomerLabel = new javax.swing.JLabel();
        confirmPasswordLabel = new javax.swing.JLabel();
        PasswordField1 = new javax.swing.JPasswordField();
        contactLabel = new javax.swing.JLabel();
        numberLabel = new javax.swing.JLabel();
        numberTextField = new javax.swing.JTextField();
        addressLabel = new javax.swing.JLabel();
        personalLabel = new javax.swing.JLabel();
        sNameLabel = new javax.swing.JLabel();
        fNameLabel = new javax.swing.JLabel();
        fNameTextField = new javax.swing.JTextField();
        sNameTextField = new javax.swing.JTextField();
        codeLabel = new javax.swing.JLabel();
        OwnerCode = new javax.swing.JPasswordField();
        showCode = new javax.swing.JLabel();
        createLabel = new javax.swing.JLabel();
        emailErrorLabel = new javax.swing.JLabel();
        numberErrorLabel = new javax.swing.JLabel();
        addressErrorLabel = new javax.swing.JLabel();
        passwordErrorLabel = new javax.swing.JLabel();
        ownerErrorLabel = new javax.swing.JLabel();
        sNameErrorLabel = new javax.swing.JLabel();
        fNameErrorLabel = new javax.swing.JLabel();
        sqlErrorLabel = new javax.swing.JLabel();
        addressTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        showPassword.setFont(new java.awt.Font("Georgia Pro Cond", 0, 20)); // NOI18N
        showPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showPasswordMouseClicked(evt);
            }
        });

        dragPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                dragPanelMouseDragged(evt);
            }
        });
        dragPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dragPanelMousePressed(evt);
            }
        });

        titleLabel.setFont(new java.awt.Font("Georgia Pro", 2, 48)); // NOI18N
        titleLabel.setText("ELMSTREET Clothing");

        exitLabel.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        exitLabel.setText("X");
        exitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout dragPanelLayout = new javax.swing.GroupLayout(dragPanel);
        dragPanel.setLayout(dragPanelLayout);
        dragPanelLayout.setHorizontalGroup(
            dragPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dragPanelLayout.createSequentialGroup()
                .addContainerGap(435, Short.MAX_VALUE)
                .addComponent(titleLabel)
                .addGap(295, 295, 295)
                .addComponent(exitLabel)
                .addContainerGap())
        );
        dragPanelLayout.setVerticalGroup(
            dragPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dragPanelLayout.createSequentialGroup()
                .addGroup(dragPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        emailLabel.setFont(new java.awt.Font("Georgia Pro Cond", 0, 20)); // NOI18N
        emailLabel.setText("Email:");

        emailTextField.setFont(new java.awt.Font("Georgia Pro Cond", 0, 20)); // NOI18N

        passwordLabel.setFont(new java.awt.Font("Georgia Pro Cond", 0, 20)); // NOI18N
        passwordLabel.setText("Password:");

        PasswordField.setFont(new java.awt.Font("Georgia Pro Cond", 0, 20)); // NOI18N

        ownerButton.setFont(new java.awt.Font("Georgia Pro Cond", 0, 20)); // NOI18N
        ownerButton.setText("Owner");
        ownerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ownerButtonActionPerformed(evt);
            }
        });

        customerButton.setFont(new java.awt.Font("Georgia Pro Cond", 0, 20)); // NOI18N
        customerButton.setText("Customer");
        customerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerButtonActionPerformed(evt);
            }
        });

        ownerOrCustomerLabel.setFont(new java.awt.Font("Georgia Pro Cond", 0, 20)); // NOI18N
        ownerOrCustomerLabel.setText("Are you a:");

        confirmPasswordLabel.setFont(new java.awt.Font("Georgia Pro Cond", 0, 20)); // NOI18N
        confirmPasswordLabel.setText("Confirm Password:");

        PasswordField1.setFont(new java.awt.Font("Georgia Pro Cond", 0, 20)); // NOI18N

        contactLabel.setFont(new java.awt.Font("Georgia Pro Cond", 0, 24)); // NOI18N
        contactLabel.setText("Contact Details");

        numberLabel.setFont(new java.awt.Font("Georgia Pro Cond", 0, 20)); // NOI18N
        numberLabel.setText("Phone Number:");

        numberTextField.setFont(new java.awt.Font("Georgia Pro Cond", 0, 20)); // NOI18N

        addressLabel.setFont(new java.awt.Font("Georgia Pro Cond", 0, 20)); // NOI18N
        addressLabel.setText("Delivery Address:");

        personalLabel.setFont(new java.awt.Font("Georgia Pro Cond", 0, 24)); // NOI18N
        personalLabel.setText("Personal Infromation");

        sNameLabel.setFont(new java.awt.Font("Georgia Pro Cond", 0, 20)); // NOI18N
        sNameLabel.setText("Surname:");

        fNameLabel.setFont(new java.awt.Font("Georgia Pro Cond", 0, 20)); // NOI18N
        fNameLabel.setText("Firstname:");

        fNameTextField.setFont(new java.awt.Font("Georgia Pro Cond", 0, 20)); // NOI18N

        sNameTextField.setFont(new java.awt.Font("Georgia Pro Cond", 0, 20)); // NOI18N

        codeLabel.setFont(new java.awt.Font("Georgia Pro Cond", 0, 20)); // NOI18N
        codeLabel.setText("Owner Code:");

        OwnerCode.setFont(new java.awt.Font("Georgia Pro Cond", 0, 20)); // NOI18N

        showCode.setFont(new java.awt.Font("Georgia Pro Cond", 0, 20)); // NOI18N
        showCode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showCodeMouseClicked(evt);
            }
        });

        createLabel.setFont(new java.awt.Font("Georgia Pro Cond", 0, 36)); // NOI18N
        createLabel.setText("Create Account");
        createLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createLabelMouseClicked(evt);
            }
        });

        emailErrorLabel.setFont(new java.awt.Font("Georgia Pro Cond", 0, 12)); // NOI18N
        emailErrorLabel.setForeground(new java.awt.Color(255, 51, 51));

        numberErrorLabel.setFont(new java.awt.Font("Georgia Pro Cond", 0, 12)); // NOI18N
        numberErrorLabel.setForeground(new java.awt.Color(255, 51, 51));

        addressErrorLabel.setFont(new java.awt.Font("Georgia Pro Cond", 0, 12)); // NOI18N
        addressErrorLabel.setForeground(new java.awt.Color(255, 51, 51));

        passwordErrorLabel.setFont(new java.awt.Font("Georgia Pro Cond", 0, 12)); // NOI18N
        passwordErrorLabel.setForeground(new java.awt.Color(255, 51, 51));

        ownerErrorLabel.setFont(new java.awt.Font("Georgia Pro Cond", 0, 12)); // NOI18N
        ownerErrorLabel.setForeground(new java.awt.Color(255, 51, 51));

        sNameErrorLabel.setFont(new java.awt.Font("Georgia Pro Cond", 0, 12)); // NOI18N
        sNameErrorLabel.setForeground(new java.awt.Color(255, 51, 51));

        fNameErrorLabel.setFont(new java.awt.Font("Georgia Pro Cond", 0, 12)); // NOI18N
        fNameErrorLabel.setForeground(new java.awt.Color(255, 51, 51));

        sqlErrorLabel.setFont(new java.awt.Font("Georgia Pro Cond", 0, 24)); // NOI18N
        sqlErrorLabel.setForeground(new java.awt.Color(255, 0, 0));

        addressTextField.setFont(new java.awt.Font("Georgia Pro Cond", 0, 14)); // NOI18N
        addressTextField.setText("e.g. 18 The Glen, 5 Simbithi Drive");
        addressTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addressTextFieldMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dragPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(contactLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(showPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(75, 75, 75)
                                                    .addComponent(emailLabel))
                                                .addComponent(numberLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                                            .addComponent(addressLabel))
                                        .addGap(12, 12, 12)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(numberTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                                            .addComponent(emailTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(addressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(126, 126, 126)
                                        .addComponent(passwordLabel))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(confirmPasswordLabel)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(PasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                                    .addComponent(PasswordField1))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(emailErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                                .addComponent(numberErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addressErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(fNameLabel)
                                    .addComponent(sNameLabel)
                                    .addComponent(ownerOrCustomerLabel))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(12, 12, 12)
                                            .addComponent(fNameTextField))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(sNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(OwnerCode, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(showCode, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(ownerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(customerButton))))))
                            .addComponent(codeLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fNameErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sNameErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ownerErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(personalLabel))
                .addGap(105, 105, 105))
            .addGroup(layout.createSequentialGroup()
                .addGap(415, 415, 415)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sqlErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dragPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(contactLabel)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(emailLabel)
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(numberLabel)
                                            .addComponent(numberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(numberErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(emailErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(personalLabel)
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(sNameLabel)
                                    .addComponent(sNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ownerOrCustomerLabel)
                                .addComponent(ownerButton)
                                .addComponent(customerButton))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(addressLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addressErrorLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addressTextField, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(showPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(passwordErrorLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(passwordLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(confirmPasswordLabel)
                                    .addComponent(PasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(showCode, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(codeLabel)
                                    .addComponent(OwnerCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(ownerErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fNameErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(fNameLabel)
                                    .addComponent(fNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sNameErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                .addComponent(sqlErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(createLabel)
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 private dbManager dbm;
    private int mouseX, mouseY;
    private boolean hidePassword = true;
    private boolean hideCode = true;
    private User u;
    private dataValidator dv;
    private void showPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showPasswordMouseClicked
        if (hidePassword == true) {
            ImageIcon ic = new ImageIcon("Resources\\hidePassword.jpg");
            showPassword.setIcon(ic);
            PasswordField.setEchoChar((char) 0);
            PasswordField1.setEchoChar((char) 0);
            hidePassword = false;
        } else {
            PasswordField.setEchoChar('*');
            PasswordField1.setEchoChar('*');
            hidePassword = true;
            ImageIcon ic = new ImageIcon("Resources\\showPassword.jpg");
            showPassword.setIcon(ic);
        }
    }//GEN-LAST:event_showPasswordMouseClicked

    private void exitLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseClicked
        new LoginSignUpScreen(dbm).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_exitLabelMouseClicked

    private void dragPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragPanelMouseDragged
        int x = evt.getXOnScreen() - mouseX;
        int y = evt.getYOnScreen() - mouseY;
        this.setLocation(x, y);
    }//GEN-LAST:event_dragPanelMouseDragged

    private void dragPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragPanelMousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_dragPanelMousePressed

    private void showCodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showCodeMouseClicked
        if (hideCode == true) {
            ImageIcon ic = new ImageIcon("Resources\\hidePassword.jpg");
            showCode.setIcon(ic);
            OwnerCode.setEchoChar((char) 0);
            hideCode = false;
        } else {
            OwnerCode.setEchoChar('*');
            hideCode = true;
            ImageIcon ic = new ImageIcon("Resources\\showPassword.jpg");
            showCode.setIcon(ic);
        }
    }//GEN-LAST:event_showCodeMouseClicked

    private void createLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createLabelMouseClicked
        // TODO add your handling code here:
        String email = emailTextField.getText();
        String number = numberTextField.getText();
        String address = addressTextField.getText();
        String password1 = PasswordField.getText();
        String password2 = PasswordField1.getText();
        String fName = fNameTextField.getText();
        String sName = sNameTextField.getText();
        boolean isOwner = false;

        boolean isValid = true; // Flag to track overall validation status

// Validate Email
        if (email.isBlank()) {
            emailErrorLabel.setText("Email is required");
            isValid = false;
        } else {
            if (!dataValidator.isValidEmail(email)) {
                emailErrorLabel.setText("Invalid email format");
                isValid = false;
            } else {
                emailErrorLabel.setText(""); // Clear error if valid
            }
        }

// Validate First Name
        if (fName.isBlank()) {
            fNameErrorLabel.setText("This field needs a minimum of two characters");
            isValid = false;
        } else {
            if (!dataValidator.isValidName(fName)) {
                fNameErrorLabel.setText("First name must contain only letters");
                isValid = false;
            } else {
                fNameErrorLabel.setText(""); // Clear error if valid
            }
        }

// Validate Surname
        if (sName.isBlank()) {
            sNameErrorLabel.setText("This field needs a minimum of two characters");
            isValid = false;
        } else {
            if (!dataValidator.isValidName(sName)) {
                sNameErrorLabel.setText("Surname must contain only letters");
                isValid = false;
            } else {
                sNameErrorLabel.setText(""); // Clear error if valid
            }
        }

// Validate Contact Number
        if (number.isBlank()) {
            numberErrorLabel.setText("Your contact number must be 10 digits long");
            isValid = false;
        } else {
            if (!dataValidator.isValidPhoneNumber(number)) {
                numberErrorLabel.setText("Invalid phone number format");
                isValid = false;
            } else {
                numberErrorLabel.setText(""); // Clear error if valid
            }
        }

// Validate Address
        if (address.isBlank()) {
            addressErrorLabel.setText("An address is required");
            isValid = false;
        } else {
            if (!dataValidator.isValidAddress(address)) {
                addressErrorLabel.setText("Invalid address format");
                isValid = false;
            } else {
                addressErrorLabel.setText(""); // Clear error if valid
            }
        }

// Validate Password
        if (password1.isBlank() || password2.isBlank()) {
            passwordErrorLabel.setText("Both fields are required");
            isValid = false;
        } else if (!dataValidator.isValidPassword(password1)) {
            passwordErrorLabel.setText("Password must be 8-16 characters and contain letters and numbers");
            isValid = false;
        } else if (!password1.equals(password2)) {
            passwordErrorLabel.setText("Passwords do not match");
            isValid = false;
        } else {
            passwordErrorLabel.setText(""); // Clear error if valid
        }

// Validate Owner Code (if Owner is selected)
        if (ownerButton.isSelected()) {
            if (OwnerCode.getText().trim().isBlank()) {
                ownerErrorLabel.setText("Owner code is required");
                isValid = false;
            } else if (OwnerCode.getText().trim().equals("2910")) {
                isOwner = true;
            }
        } else {
            ownerErrorLabel.setText(""); // Clear error if valid
        }

// Final validation check
        if (isValid) {
            try {
                System.out.println(number);
                if(u.createUser(isOwner, fName+" "+sName, number, address, email, password1,dbm)){
                    java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                            try {
                                new MainScreen(u,dbm).setVisible(true);
                            } catch (ClassNotFoundException ex) {
                            } catch (SQLException ex) {
                            }
                        }
                    });
                    sqlErrorLabel.setText("");
                    this.dispose();
                }else{
                    sqlErrorLabel.setText("This email is already in use");
                }
            } catch (SQLException ex) {
            }
        }


    }//GEN-LAST:event_createLabelMouseClicked

    private void ownerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ownerButtonActionPerformed
        // TODO add your handling code here:
        showOwnerCodeField(true);

    }//GEN-LAST:event_ownerButtonActionPerformed

    private void customerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerButtonActionPerformed
        // TODO add your handling code here:
        showOwnerCodeField(false);
    }//GEN-LAST:event_customerButtonActionPerformed

    private void addressTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addressTextFieldMouseClicked
        // TODO add your handling code here:
        if (addressTextField.getText().equals("e.g. 18 The Glen, 5 Simbithi Drive")) {
            addressTextField.setText("");
        }
    }//GEN-LAST:event_addressTextFieldMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField OwnerCode;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JPasswordField PasswordField1;
    private javax.swing.JLabel addressErrorLabel;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField addressTextField;
    private javax.swing.JLabel codeLabel;
    private javax.swing.JLabel confirmPasswordLabel;
    private javax.swing.JLabel contactLabel;
    private javax.swing.JLabel createLabel;
    private javax.swing.JRadioButton customerButton;
    private javax.swing.ButtonGroup customerOwnerbuttonGroup;
    private javax.swing.JPanel dragPanel;
    private javax.swing.JLabel emailErrorLabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel exitLabel;
    private javax.swing.JLabel fNameErrorLabel;
    private javax.swing.JLabel fNameLabel;
    private javax.swing.JTextField fNameTextField;
    private javax.swing.JLabel numberErrorLabel;
    private javax.swing.JLabel numberLabel;
    private javax.swing.JTextField numberTextField;
    private javax.swing.JRadioButton ownerButton;
    private javax.swing.JLabel ownerErrorLabel;
    private javax.swing.JLabel ownerOrCustomerLabel;
    private javax.swing.JLabel passwordErrorLabel;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel personalLabel;
    private javax.swing.JLabel sNameErrorLabel;
    private javax.swing.JLabel sNameLabel;
    private javax.swing.JTextField sNameTextField;
    private javax.swing.JLabel showCode;
    private javax.swing.JLabel showPassword;
    private javax.swing.JLabel sqlErrorLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables

    private void showOwnerCodeField(Boolean show) {
        OwnerCode.setVisible(show);
        showCode.setVisible(show);
        codeLabel.setVisible(show);
    }
}
