/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.working;

import UI.working.LoginSignUpScreen;
import Backend.working.User;
import Backend.dbManager;
import UI.MainScreen;
import java.awt.Color;
import java.sql.SQLException;


/**
 *
 * @author Kairav
 */
public class InfoScreen extends javax.swing.JFrame {

    /**
     * Creates new form InfoScreen
     */
    public InfoScreen(User inU, dbManager inManager) {
        dbm=inManager;
        initComponents();
        this.setLocationRelativeTo(null);
        infoTextArea.setCaretColor(Color.red);
        u=inU;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        infoTextArea = new javax.swing.JTextArea();
        dragPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        exitLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(222, 222, 222));
        setUndecorated(true);

        infoTextArea.setBackground(new java.awt.Color(222, 222, 222));
        infoTextArea.setColumns(20);
        infoTextArea.setFont(new java.awt.Font("Georgia Pro Cond Light", 0, 18)); // NOI18N
        infoTextArea.setRows(5);
        infoTextArea.setText("ELMSTREET Clothing is more than a clothing brand.\n\nIt's a bussiness lead by young South African entrepreneurs. \nWe offers a unique experience to our customers at the best \nprice possible. \nELMSTREET clothing specialises in a wide array of t-shirts \nwhich fit into one of three catagories; namely automotive, \nmemes and music artists. \nIn addition to our wide range of aparell options we offer  local \ndelivery at no extra charge.\n\nDisclaimer: At this time we only accept cash payments\n\nContact us on Instagram: @elmstreetclothing\n\nPress F1 to return to this screen\n\n\n");
        infoTextArea.setToolTipText("");
        infoTextArea.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        infoTextArea.setEnabled(false);
        infoTextArea.setMinimumSize(new java.awt.Dimension(420, 168));
        infoTextArea.setOpaque(false);

        dragPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                dragPanelMouseDragged(evt);
            }
        });
        dragPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dragPanelMousePressed(evt);
            }
        });

        titleLabel.setFont(new java.awt.Font("Georgia Pro", 2, 48)); // NOI18N
        titleLabel.setText("ELMSTREET Clothing");

        exitLabel.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        exitLabel.setText("X");
        exitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout dragPanelLayout = new javax.swing.GroupLayout(dragPanel);
        dragPanel.setLayout(dragPanelLayout);
        dragPanelLayout.setHorizontalGroup(
            dragPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dragPanelLayout.createSequentialGroup()
                .addGap(309, 309, 309)
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 274, Short.MAX_VALUE)
                .addComponent(exitLabel)
                .addContainerGap())
        );
        dragPanelLayout.setVerticalGroup(
            dragPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(exitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dragPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(infoTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(327, 327, 327))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dragPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(infoTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 private boolean signedin;
 private User u;
 private dbManager dbm;
 
    private void exitLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseClicked
        // TODO add your handling code here:
        if (u.isSignedin()) {
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    try {
                        new MainScreen(u,dbm).setVisible(true);
                    } catch (ClassNotFoundException ex) {
                    } catch (SQLException ex) {
                    }
                }
            });
        }else{
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new LoginSignUpScreen(dbm).setVisible(true);
                }
            });
        }
        this.dispose();
    }//GEN-LAST:event_exitLabelMouseClicked
    private int mouseX, mouseY;
    private void dragPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragPanelMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen() - mouseX;
        int y = evt.getYOnScreen() - mouseY;
        this.setLocation(x, y);
    }//GEN-LAST:event_dragPanelMouseDragged

    private void dragPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragPanelMousePressed
        // TODO add your handling code here:
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_dragPanelMousePressed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel dragPanel;
    private javax.swing.JLabel exitLabel;
    private javax.swing.JTextArea infoTextArea;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
