/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.working;

import Backend.working.Item;
import Backend.working.User;
import Backend.dbManager;
import UI.MainScreen;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Kairav
 */
public class ItemScreen extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public ItemScreen(User inU, Item inI, dbManager inManager) {
        initComponents();
        this.setLocationRelativeTo(null);
        dbm = inManager;
        u = inU;
        i = inI;
        SpinnerModel priceSpinnerModel = null;
        SpinnerModel stockSpinnerModel = null;
        SpinnerModel discountSpinnerModel = null;
        categoryComboBox.setSelectedIndex(i.getCategory());
        nameTextField.setText(i.getName());
        int itemsInStock = i.getQuantity();

        if (itemsInStock == 0) {
            addOrUpdateButton.setVisible(false);
            itemsSpinner.setVisible(false);
        }

        if (u.isOwner()) {
            priceSpinnerModel = new SpinnerNumberModel(i.getSellingPrice(), 1, 999, 0.5);
            stockSpinnerModel = new SpinnerNumberModel(itemsInStock, 0, 100000000, 1);
            discountSpinnerModel = new SpinnerNumberModel(i.getDiscount(), 0, 99, 1);
            discountSpinner.setModel(discountSpinnerModel);
            addOrUpdateButton.setText("Update Item");
            itemsSpinner.setVisible(false);
            itemDiscountLabel.setVisible(false);
            itemDiscountLabelOwner.setVisible(true);
        } else {
            priceSpinnerModel = new SpinnerNumberModel(i.getCurrentPrice(), 1, 999, 0);
            stockSpinnerModel = new SpinnerNumberModel(itemsInStock, itemsInStock, 100000000, 0);
            itemDiscountLabelOwner.setVisible(false);
            discountSpinner.setVisible(false);
            nameTextField.setEditable(false);
            itemPriceLabel.setText("Price: R");
            itemDiscountLabel.setText("For a limited time only save " + i.getDiscount() + "%");
            categoryComboBox.setEditable(false);
            if (inI.getDiscount() == 0) {
                itemDiscountLabel.setVisible(false);
            }
        }

        itemsSpinner.setModel(new SpinnerNumberModel(0, 0, itemsInStock, 1));
        priceSpinner.setModel(priceSpinnerModel);
        stockSpinner.setModel(stockSpinnerModel);
        itemImage.setIcon(new ImageIcon(i.getImagePath() + ".jpg"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        itemImage = new javax.swing.JLabel();
        itemPriceLabel = new javax.swing.JLabel();
        itemNameLabel = new javax.swing.JLabel();
        stockLabel = new javax.swing.JLabel();
        itemDiscountLabel = new javax.swing.JLabel();
        dragPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        exitLabel = new javax.swing.JLabel();
        itemCategoryLabel = new javax.swing.JLabel();
        itemsSpinner = new javax.swing.JSpinner();
        addOrUpdateButton = new javax.swing.JButton();
        nameTextField = new javax.swing.JTextField();
        stockSpinner = new javax.swing.JSpinner();
        categoryComboBox = new javax.swing.JComboBox<>();
        priceSpinner = new javax.swing.JSpinner();
        discountSpinner = new javax.swing.JSpinner();
        itemDiscountLabelOwner = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        itemImage.setFont(new java.awt.Font("Georgia Pro Cond", 0, 14)); // NOI18N
        itemImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        itemImage.setIcon(new javax.swing.ImageIcon("C:\\Users\\Kairav\\OneDrive\\Documents\\NetBeansProjects\\ElmStreet\\Resources\\porsche.jpg")); // NOI18N

        itemPriceLabel.setFont(new java.awt.Font("Georgia Pro Cond", 0, 14)); // NOI18N
        itemPriceLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        itemPriceLabel.setText("Original Price: R");

        itemNameLabel.setFont(new java.awt.Font("Georgia Pro Cond", 0, 14)); // NOI18N
        itemNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        itemNameLabel.setText("Name: ");

        stockLabel.setFont(new java.awt.Font("Georgia Pro Cond", 0, 14)); // NOI18N
        stockLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        stockLabel.setText("Stock:");

        itemDiscountLabel.setFont(new java.awt.Font("Georgia Pro Cond", 0, 14)); // NOI18N
        itemDiscountLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        itemDiscountLabel.setText("For a limited time save");

        dragPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                dragPanelMouseDragged(evt);
            }
        });
        dragPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dragPanelMousePressed(evt);
            }
        });

        titleLabel.setFont(new java.awt.Font("Georgia Pro", 2, 36)); // NOI18N
        titleLabel.setText("ELMSTREET Clothing");

        exitLabel.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        exitLabel.setText("X");
        exitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout dragPanelLayout = new javax.swing.GroupLayout(dragPanel);
        dragPanel.setLayout(dragPanelLayout);
        dragPanelLayout.setHorizontalGroup(
            dragPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dragPanelLayout.createSequentialGroup()
                .addContainerGap(449, Short.MAX_VALUE)
                .addComponent(titleLabel)
                .addGap(377, 377, 377)
                .addComponent(exitLabel)
                .addContainerGap())
        );
        dragPanelLayout.setVerticalGroup(
            dragPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dragPanelLayout.createSequentialGroup()
                .addGroup(dragPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleLabel)
                    .addComponent(exitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        itemCategoryLabel.setFont(new java.awt.Font("Georgia Pro Cond", 0, 14)); // NOI18N
        itemCategoryLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        itemCategoryLabel.setText("Category:");

        itemsSpinner.setFont(new java.awt.Font("Georgia Pro Cond", 0, 18)); // NOI18N

        addOrUpdateButton.setFont(new java.awt.Font("Georgia Pro Cond", 0, 18)); // NOI18N
        addOrUpdateButton.setText("Add to cart");
        addOrUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOrUpdateButtonActionPerformed(evt);
            }
        });

        stockSpinner.setFont(new java.awt.Font("Georgia Pro Cond", 0, 14)); // NOI18N

        categoryComboBox.setFont(new java.awt.Font("Georgia Pro Cond", 0, 14)); // NOI18N
        categoryComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Automotives", "Rappers", "Humour", " " }));

        priceSpinner.setFont(new java.awt.Font("Georgia Pro Cond", 0, 14)); // NOI18N

        discountSpinner.setFont(new java.awt.Font("Georgia Pro Cond", 0, 14)); // NOI18N

        itemDiscountLabelOwner.setFont(new java.awt.Font("Georgia Pro Cond", 0, 14)); // NOI18N
        itemDiscountLabelOwner.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        itemDiscountLabelOwner.setText("Discount percent:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dragPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(456, 456, 456)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(itemImage, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(itemPriceLabel)
                                .addGap(2, 2, 2)
                                .addComponent(priceSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(itemCategoryLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(categoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(itemDiscountLabelOwner)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(discountSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(itemDiscountLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(itemNameLabel)
                                    .addGap(3, 3, 3)
                                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(stockLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(stockSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(563, 563, 563)
                        .addComponent(addOrUpdateButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(itemsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dragPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(itemImage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemNameLabel)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stockLabel)
                    .addComponent(stockSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemCategoryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemPriceLabel)
                    .addComponent(priceSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(itemDiscountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(discountSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemDiscountLabelOwner))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addOrUpdateButton)
                    .addComponent(itemsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 private dbManager dbm;

    private void exitLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseClicked
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainScreen(u, dbm).setVisible(true);
                } catch (ClassNotFoundException ex) {
                } catch (SQLException ex) {
                }
            }
        });
        this.dispose();
    }//GEN-LAST:event_exitLabelMouseClicked
    private int mouseX, mouseY;
    private User u;
    private Item i;
    private void dragPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragPanelMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen() - mouseX;
        int y = evt.getYOnScreen() - mouseY;
        this.setLocation(x, y);
    }//GEN-LAST:event_dragPanelMouseDragged

    private void dragPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragPanelMousePressed
        // TODO add your handling code here:
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_dragPanelMousePressed

    private void addOrUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOrUpdateButtonActionPerformed
        try {
            // TODO add your handling code here:
            int changeInStock=(int)stockSpinner.getValue()-i.getQuantity();
            int itemCategory=categoryComboBox.getSelectedIndex();
            int discountPercentage=(int)discountSpinner.getValue();
            double price=(double)priceSpinner.getValue();
            String name=nameTextField.getText();

            dbm.UpdateItem(i.getItemID(), changeInStock, name, discountPercentage, itemCategory, price);
            if (!u.isOwner()) {
                //add to cart
                
                
            }
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    try {
                        new MainScreen(u, dbm).setVisible(true);
                    } catch (ClassNotFoundException | SQLException ex) {
                    }
                }
            });
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(ItemScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addOrUpdateButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addOrUpdateButton;
    private javax.swing.JComboBox<String> categoryComboBox;
    private javax.swing.JSpinner discountSpinner;
    private javax.swing.JPanel dragPanel;
    private javax.swing.JLabel exitLabel;
    private javax.swing.JLabel itemCategoryLabel;
    private javax.swing.JLabel itemDiscountLabel;
    private javax.swing.JLabel itemDiscountLabelOwner;
    private javax.swing.JLabel itemImage;
    private javax.swing.JLabel itemNameLabel;
    private javax.swing.JLabel itemPriceLabel;
    private javax.swing.JSpinner itemsSpinner;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JSpinner priceSpinner;
    private javax.swing.JLabel stockLabel;
    private javax.swing.JSpinner stockSpinner;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
