/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.working;

import javax.swing.JFrame;
import javax.swing.Timer;
import Backend.working.ChatGPTAPI;
import Backend.working.DB;
import Backend.dbManager;
import java.awt.Font;
import java.sql.SQLException;
import javax.swing.JLabel;

/**
 *
 * @author Kairav
 */
public class SplashScreen extends javax.swing.JFrame {

    /**
     * Creates new form SplashScreen
     */
    public SplashScreen() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setOpacity(0.0f);
        try {
            DB.init();
        } catch (ClassNotFoundException | SQLException ex) {
        }
        dbm = new dbManager();
        ChatGPTAPI c = new ChatGPTAPI();
        // Set the quote text
        
//        JLabel label = sloganLabel1;
//        String quote = c.GenQuote();
//        resizeQuote(label, quote);
    }

    private static dbManager dbm;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sloganLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        sloganLabel1 = new javax.swing.JLabel();

        sloganLabel.setFont(new java.awt.Font("High Tower Text", 2, 20)); // NOI18N
        sloganLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sloganLabel.setText("Shift Your Style");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        titleLabel.setFont(new java.awt.Font("Georgia Pro Cond", 0, 36)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("ELMSTREET");

        sloganLabel1.setFont(new java.awt.Font("High Tower Text", 2, 20)); // NOI18N
        sloganLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sloganLabel1.setText("Shift Your Style");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 868, Short.MAX_VALUE)
                    .addComponent(sloganLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(titleLabel)
                .addGap(48, 48, 48)
                .addComponent(sloganLabel1)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                JFrame frame = new SplashScreen();
                frame.setVisible(true);

                Timer t = new Timer(30, e -> {
                    float opacity = frame.getOpacity();
                    if (opacity < 1.0f) {
                        frame.setOpacity(Math.min(opacity + 0.02f, 1.0f));

                    } else {
                        ((Timer) e.getSource()).stop();
                        try {
                            Thread.sleep(10);

                        } catch (InterruptedException ex) {
                        }
                        frame.dispose();
                        new LoginSignUpScreen(dbm).setVisible(true);
                    }
                });
                t.start();
            }
        });
    }

    private void resizeQuote(JLabel label, String quote) {

        label.setText("<html>" + quote + "</html>");

        // Calculate an initial font size based on the length of the quote
        int baseFontSize = 30; // Base font size for the quote
        Font font = label.getFont();

        // Get the width of the label and the length of the quote
        int labelWidth = 856;  // Width of the label in pixels
        int quoteLength = quote.length();

        // Calculate an estimated font size based on quote length and label width
        int fontSize = Math.max(baseFontSize, labelWidth / (quoteLength / 2));

        // Set the font size dynamically
        font = new Font(font.getName(), Font.PLAIN, fontSize);
        label.setFont(font);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel sloganLabel;
    private javax.swing.JLabel sloganLabel1;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
