/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Backend.Cart;
import Backend.working.User;
import Backend.dbManager;
import Backend.working.Item;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JList;
import javax.swing.ListModel;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Kairav
 */
public class CartScreen extends javax.swing.JFrame {

    /**
     * Creates new form CartScreen
     */
    public CartScreen(User inU, Cart inC, dbManager inManager) {
        try {
            initComponents();
            this.setLocationRelativeTo(null);
            u = inU;
            c = inC;
            dbm = inManager;
            items = c.getItemsInCart();
            Item currentItem = items.get(0);
            itemImage.setIcon(new ImageIcon(currentItem.getImagePath() + ".jpg"));
            itemNameLabel1.setText(currentItem.getName());
            valueLabel.setText("R " + currentItem.getCurrentPrice());
            quantitySpinner.setModel(new SpinnerNumberModel(currentItem.getQuantity(), 1, currentItem.getStock(dbm), 1));
            cartValueLabel1.setText("R "+c.getCartValue());
            String[] itemNames = new String[items.size()];
            for (int i = 0; i < items.size(); i++) {
                itemNames[i] = items.get(i).getName();
            }
            DefaultListModel<String> listModel = new DefaultListModel<>();
            for (Item item : items) {
                listModel.addElement(item.getName());
            }
            
            // Step 3: Create the JList with names
            itemList.setModel(listModel);
        } catch (SQLException ex) {
            Logger.getLogger(CartScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner2 = new javax.swing.JSpinner();
        titleLabel = new javax.swing.JLabel();
        itemImage = new javax.swing.JLabel();
        viewLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        itemList = new javax.swing.JList<>();
        contentsLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        placeOrderButton = new javax.swing.JButton();
        cartValueLabel = new javax.swing.JLabel();
        itemNameLabel = new javax.swing.JLabel();
        quantityLabel = new javax.swing.JLabel();
        quantitySpinner = new javax.swing.JSpinner();
        valueLabel1 = new javax.swing.JLabel();
        itemNameLabel1 = new javax.swing.JLabel();
        cartValueLabel1 = new javax.swing.JLabel();
        exitLabel = new javax.swing.JLabel();
        itemDeliveryLabel = new javax.swing.JLabel();
        insufficientStockLablel = new javax.swing.JLabel();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLabel.setFont(new java.awt.Font("Georgia Pro Cond", 0, 36)); // NOI18N
        titleLabel.setText("Your Cart");

        itemImage.setFont(new java.awt.Font("Georgia Pro Cond", 0, 14)); // NOI18N
        itemImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        itemImage.setIcon(new javax.swing.ImageIcon("C:\\Users\\Kairav\\OneDrive\\Documents\\NetBeansProjects\\ElmStreet\\Resources\\porsche.jpg")); // NOI18N

        viewLabel.setFont(new java.awt.Font("Georgia Pro Cond", 0, 14)); // NOI18N
        viewLabel.setText("View Item");
        viewLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewLabelMouseClicked(evt);
            }
        });

        jScrollPane2.setViewportView(itemList);

        contentsLabel.setFont(new java.awt.Font("Georgia Pro Cond", 0, 24)); // NOI18N
        contentsLabel.setText("Contents:");

        valueLabel.setFont(new java.awt.Font("Georgia Pro Cond", 0, 24)); // NOI18N
        valueLabel.setText("Item Value: ");

        placeOrderButton.setFont(new java.awt.Font("Georgia Pro Cond", 0, 18)); // NOI18N
        placeOrderButton.setText("Order");
        placeOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeOrderButtonActionPerformed(evt);
            }
        });

        cartValueLabel.setFont(new java.awt.Font("Georgia Pro Cond", 0, 24)); // NOI18N
        cartValueLabel.setText("Cart Value: ");

        itemNameLabel.setFont(new java.awt.Font("Georgia Pro Cond", 0, 24)); // NOI18N
        itemNameLabel.setText("Item Name:");

        quantityLabel.setFont(new java.awt.Font("Georgia Pro Cond", 0, 24)); // NOI18N
        quantityLabel.setText(" Quantity of  item:");

        valueLabel1.setFont(new java.awt.Font("Georgia Pro Cond", 0, 24)); // NOI18N

        itemNameLabel1.setFont(new java.awt.Font("Georgia Pro Cond", 0, 24)); // NOI18N
        itemNameLabel1.setText(" ");

        cartValueLabel1.setFont(new java.awt.Font("Georgia Pro Cond", 0, 24)); // NOI18N

        exitLabel.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        exitLabel.setText("X");
        exitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLabelMouseClicked(evt);
            }
        });

        itemDeliveryLabel.setFont(new java.awt.Font("Georgia Pro Cond", 0, 14)); // NOI18N
        itemDeliveryLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        itemDeliveryLabel.setText("Should be delivered by 31 January (15 days time)");

        insufficientStockLablel.setFont(new java.awt.Font("Georgia Pro Cond", 0, 14)); // NOI18N
        insufficientStockLablel.setForeground(new java.awt.Color(255, 0, 0));
        insufficientStockLablel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        insufficientStockLablel.setText("Your order cannot be fufilled at this time ");

        updateButton.setFont(new java.awt.Font("Georgia Pro Cond", 0, 18)); // NOI18N
        updateButton.setText("Update Cart");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        deleteButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Kairav\\OneDrive\\Documents\\NetBeansProjects\\ElmStreet\\Resources\\deleteIcon.png")); // NOI18N
        deleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(133, 133, 133)
                                .addComponent(titleLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(quantityLabel)
                                                .addComponent(itemNameLabel)
                                                .addComponent(contentsLabel))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(61, 61, 61)
                                                .addComponent(valueLabel))
                                            .addComponent(cartValueLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(quantitySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(valueLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(cartValueLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))
                                                    .addComponent(itemNameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(viewLabel)
                                                    .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(81, 81, 81)
                                        .addComponent(itemDeliveryLabel)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(updateButton)
                        .addGap(161, 161, 161)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(insufficientStockLablel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(itemImage, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE))
                        .addGap(80, 80, 80)
                        .addComponent(exitLabel)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(placeOrderButton)
                        .addGap(229, 229, 229))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(itemImage))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(titleLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(exitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(itemNameLabel)
                                .addComponent(itemNameLabel1))
                            .addComponent(deleteButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(valueLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(valueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(quantityLabel)
                            .addComponent(quantitySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cartValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cartValueLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(contentsLabel)
                            .addComponent(viewLabel)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(itemDeliveryLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(insufficientStockLablel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(placeOrderButton))
                    .addComponent(updateButton)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private User u;
    private Cart c;
    private dbManager dbm;
    private ArrayList<Item> items;
    private void placeOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeOrderButtonActionPerformed
        try {
            // TODO add your handling code here:
            dbm.newCart(u.getUserID());
            //add

            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    try {
                        new MainScreen(u, dbm).setVisible(true);
                    } catch (ClassNotFoundException | SQLException ex) {
                    }
                }
            });
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(CartScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_placeOrderButtonActionPerformed

    private void exitLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseClicked
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    try {
                        new MainScreen(u, dbm).setVisible(true);
                    } catch (SQLException ex) {
                    }
                } catch (ClassNotFoundException ex) {
                }
            }
        });
        this.dispose();
    }//GEN-LAST:event_exitLabelMouseClicked

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateButtonActionPerformed

    private void deleteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteButtonMouseClicked

    private void viewLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewLabelMouseClicked
        try {
            // TODO add your handling code here:
            int selectedIndex = itemList.getSelectedIndex();
            Item currentItem = items.get(selectedIndex);
            itemImage.setIcon(new ImageIcon(currentItem.getImagePath() + ".jpg"));
            itemNameLabel1.setText(currentItem.getName());
            valueLabel.setText("R " + currentItem.getCurrentPrice());
            quantitySpinner.setModel(new SpinnerNumberModel(currentItem.getQuantity(), 1, currentItem.getStock(dbm), 1));
        } catch (SQLException ex) {
            Logger.getLogger(CartScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_viewLabelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cartValueLabel;
    private javax.swing.JLabel cartValueLabel1;
    private javax.swing.JLabel contentsLabel;
    private javax.swing.JLabel deleteButton;
    private javax.swing.JLabel exitLabel;
    private javax.swing.JLabel insufficientStockLablel;
    private javax.swing.JLabel itemDeliveryLabel;
    private javax.swing.JLabel itemImage;
    private javax.swing.JList<String> itemList;
    private javax.swing.JLabel itemNameLabel;
    private javax.swing.JLabel itemNameLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JButton placeOrderButton;
    private javax.swing.JLabel quantityLabel;
    private javax.swing.JSpinner quantitySpinner;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton updateButton;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JLabel valueLabel1;
    private javax.swing.JLabel viewLabel;
    // End of variables declaration//GEN-END:variables
}
